name: CI
on:
  push:
    branches:
      - master
jobs:
  test:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: npm install, build, test and publish
        run: |
          npm install
          npm run build
      - name: GitHub Action for npm
        uses: actions/npm@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
#      - name: npm version
#        run: |
#          npm version patch
#          git commit -m "Release"
#          git push
#      - name: npm publish
#        run: npm publish
